########################################################

# Rainbomizer - A (probably fun) Grand Theft Auto San Andreas Mod that
#               randomizes stuff
# Copyright (C) 2019 - Parik

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#######################################################

# General Configuration

Enabled   = true
Seed      = -1 # -1 for random

Unprotect = true
AutosaveSlot = 8 # Set it to a non-existant slot (eg. -1 or 9) to disable

#######################################################
# Traffic Randomizer
[TrafficRandomizer]

Enabled = true

# This will make a specific vehicle spawn on streets
ForcedVehicleEnabled = false
ForcedVehicleID = 500

EnableTrains = true
EnableBoats = true
EnableAircrafts = true
EnableCars = true
EnableBikes = true
EnableTrailers = true

# For special vehicles on street that can't spawn peds
DefaultModel = 0

#######################################################
[ColourRandomizer]

Enabled = true
RandomizeFades = false
RainbowText = true
RainbowHueCycle = false
CrazyMode = false # You don't want this, trust me ;)
Exceptions = [0, 1] # These colours will not be randomized

#######################################################
[PoliceHeliRandomizer]
Enabled = true

#######################################################
[CheatRandomizer]

Enabled = true
EnableEasterEgg = true

#######################################################
# Experimental - Crashes are quite often
[HandlingRandomizer]

Enabled = false

#######################################################
[WeaponRandomizer]

Enabled = true
RandomizePlayerWeapons = true
SkipChecks = false # Checks related to weapons required for certain missions
                   # You might not be able to complete some missions
				   # without this enabled.

# Pattern checks
Patterns = [
	{ thread = "drugs4", ped = 0, weapon = 30, allowed = ["slot"]},
	{ thread = "finalec", ped = 0, weapon = 28, allowed = ["slot"]},
	{ thread = "drugs1", weapon = 28, allowed = ["slot"]},
	{ weapon = 43, allowed = [43]},
	{ weapon = 44, allowed = [44, 45]},
	{ thread = "sweet1", weapon = 41, allowed = [41]},
	{ thread = "heist5", weapon = 38, allowed = ["slot"]},
	{ thread = "zero1", weapon = 38, allowed = ["slot"]},
	{ thread = "casino6", weapon = 37, allowed = [37]},
	{ thread = "casino6", weapon = 37, allowed = [37]},
	{ thread = "shrange", allowed = ["slot"]},
	{ thread = "truth2", weapon = 37, allowed = [37]},
	{ thread = "truth2", weapon = 35, allowed = [35, 36, 38]},
	{ thread = "des10", ped = 0, allowed = [28, 32]},
	{ thread = "casino9", weapon = 22, allowed = [22, 23, 24]},
	{ thread = "heist9", ped = 0, weapon = 17, allowed = [17]},
	{ weapon = 39, allowed = [39]},
	{ weapon = 46, allowed = [46]}
]

#######################################################
[PickupsRandomizer]

Enabled = false
ReplaceWithWeaponsOnly = true # Does nothing yet

#######################################################
[ParkedCarRandomizer]

Enabled = true
RandomizeFixedSpawns = true
RandomizeRandomSpawns = true

#######################################################
[MissionRandomizer]

Enabled = false

#######################################################
[CutsceneRandomizer]

Enabled = false
CutsceneFile = "Cutscene_Models.txt"

#######################################################
[BlipsRandomizer]

Enabled = true

#######################################################
[ParticleRandomizer]

Enabled = false

#######################################################
[LicensePlateRandomizer]

Enabled = true

#######################################################
[SoundsRandomizer] # Random Dialogues for now

Enabled = true
MatchSubtitles = true
AudioEventsFile = "data/AudioEvents.txt" # Relative to game directory
ForceAudioLineEnabled = false
ForceAudioLine = 0

#######################################################
[ScriptVehicleRandomizer]

Enabled = true
SkipChecks = false  # Don't enable this if you don't want to softlock every
                    # other mission :P
Patterns = [

	# Mission specific-patterns

	{vehicle = 487, allowed = ["helis", "planes"], thread = "cprace", seat_check = false},
	{thread = "dschool", vehicle = 429, allowed = [429, 541, 480, 494, 506, 451]},
	{coords  = [-2584, 2213, 0], vehicle = 539, allowed = [460, 539]},
	{thread = "boat", vehicle = 539, allowed = ["460", "539", "boats"], move  = [-60, 0, 0, 0]},
    {vehicle = 487, allowed = ["all"], seat_check = false},
	{vehicle = 406, allowed = [406]},
	{vehicle = 486, allowed = [486]},
	{vehicle = 489, allowed = ["cars"]},
	{vehicle = 581, thread = "drugs1", allowed = ["bikes", "594"]},
	{thread = "bskool", vehicle = 521, allowed = ["bikes"]},
	{vehicle = 522, allowed = ["bikes"]},
	{vehicle = 601, allowed = [601]},
	{vehicle = 524, allowed = [524]},
	{vehicle = 501, allowed = [465, 501]},
	{vehicle = 530, allowed = [530]},
	{coords = [323, 2540, 15], vehicle = 476, move = [0, -35, 0, 0], allowed = ["planes"], denied = ["rc"]},
	{thread = "drugs4", vehicle = 514, allowed = ["all"], seat_check = false},
	{thread = "drugs4", vehicle = 584, allowed = ["all"], seat_check = false},
	{vehicle = 514, allowed = [514, 515, 403]},
	{vehicle = 515, allowed = [514, 515, 403]},
	{vehicle = 403, allowed = [514, 515, 403]},
	{vehicle = 478, coords = [2107, 1409, 9], allowed = [
			602, 496, 401, 518, 527, 419, 587, 533, 526, 474, 600, 445, 507,
            439, 549, 491, 422, 605, 572, 478, 554, 536, 575, 534, 534, 567,
            535, 576, 412, 402, 542, 603, 475, 429, 541, 415, 480, 562, 434,
            494, 502, 503, 411, 559, 560, 506, 541, 558, 555, 477, 546, 550
	], seat_check = false},
	{vehicle = 544, allowed = ["all"], seat_check = false, denied = ["trains", "boats"]},
	{vehicle = 567, coords = [2644, -2028, 12], allowed = [
			536, 575, 534, 567, 535, 576, 412, 566
	], seat_check = false},
	{vehicle = 584, allowed = [435, 450, 591, 584]},
	{vehicle = 435, allowed = [435, 450, 591, 584]},
	{vehicle = 450, allowed = [435, 450, 591, 584]},
	{vehicle = 591, allowed = [435, 450, 591, 584]},
	{vehicle = 510, coords = [-2171, -2422, 33], allowed = [510]},
	{vehicle = "bmx", allowed = ["cars", "bikes"], denied = [428, 443, 406]},
	{vehicle = 425, allowed = [425, 520]},
	{vehicle = 520, allowed = [520]},
	{vehicle = 425, allowed = [425, 520]},
	{vehicle = 539, coords = [-7, -1116, 7], move = [40, 0, -6, 0], allowed = ["boats", "539"], seat_check = false}, # Player
	{vehicle = 539, coords = [-7, -1111, 6], allowed = ["all"], seat_check = false},  # OG Loc
	{vehicle = 539, coords = [-4, -1120, 7], allowed = ["boats", "539", "464", "501", "465"]}, # Madd Dogg
	{vehicle = 593, coords = [1279, 1361, 9], move = [50, 0, 0, -90], allowed = ["planes"], denied = ["rc"]},
	{vehicle = 553, allowed = ["planes"], denied = ["rc"]},
	{coords = [1479, 1758, 12], vehicle = 519, allowed = ["planes"], denied = ["rc"]},
	
	# General Patterns
	{vehicle = "cars", allowed = ["cars", "bikes"]},
	{vehicle = "helis", allowed = ["helis"]},
	{vehicle = "planes", allowed = ["planes"], denied = [539]},
	{vehicle = "boats", allowed = ["boats", "539"]},
	{vehicle = "bikes", allowed = ["bikes", "cars"]}
]
